version: "3.7"

services:
  nginx:
    image: nginx:1.19
    ports:
      - 80:80
    volumes:
      - .:/var/www/myapp
      - ./nginx/dev:/etc/nginx/templates
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/myapp

  node:
    build: .
    command: gulp watch
    volumes:
      - ./dist:/app/dist
